### ISSUE TITLE
Add auto select

### ISSUE THREAD

**Issue by Gummiees** [lunapaint/vscode-luna-paint#100]
Issue Type: <b>Feature Request</b>

It would be awesome to have a tool that can auto select an area based on it's color, so it's easier to erase or paint, for instance.

Extension version: 0.9.0
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Tyriar** [comment]
👍 that's this one: https://github.com/lunapaint/vscode-luna-paint/issues/93
