### ISSUE TITLE
resize image

### ISSUE THREAD

**Issue by MattHoag-MS** [lunapaint/vscode-luna-paint#104]
Resizing an image in Luna Paint  would help with the mark down document creation in github (used by docs.microsoft.com) so that another image editor would not be required.

**Comment by mslinn** [comment]
Is there a way to resize proportionally? For example, specify new width, with automatically computed height.

**Comment by Tyriar** [comment]
@mslinn right now the fastest way of doing that is running the resize image command and then entering 50%, enter, 50%
