### ISSUE TITLE
Feature: auto refresh when file is modified.

### ISSUE THREAD

**Issue by GAZ082** [lunapaint/vscode-luna-paint#105]
Hey there. Would be nice to have the opened file to refresh automatically when modified by other program or process.

Thanks!

**Comment by Tyriar** [comment]
Looks like a VS Code issue, created microsoft/vscode#137574

**Comment by Tyriar** [comment]
While it is a VS Code/parcel watcher issue, it looks like I can work around it by treating file create events as updates.

**Comment by Tyriar** [comment]
Made another change in 0.14 that fixes watching files outside of the workspace.
