### ISSUE TITLE
Extension claims to be "built into VS Code"

### ISSUE THREAD

**Issue by gjsjohnmurray** [lunapaint/vscode-luna-paint#106]
![image](https://user-images.githubusercontent.com/6726799/142255300-78cd7dce-c991-442f-a080-e7bb181b731e.png)

I don't think it is one of the built-in extensions.

**Comment by Tyriar** [comment]
Install it to have an image editor "built in" via the webview API is what the intent was, doesn't seem particularly ambiguous to me?

**Comment by gjsjohnmurray** [comment]
"built-in" has a specific meaning though:

![image](https://user-images.githubusercontent.com/6726799/142292893-f7f0e3af-53fd-4f03-8484-70f2b631b8be.png)

I know your text uses the term "built into", so not strictly the same. But perhaps "integrated into" or "integrated with" would do.
