### ISSUE TITLE
New Icon/Image command fails when no folder is opened

### ISSUE THREAD

**Issue by MikeTheGreat** [lunapaint/vscode-luna-paint#107]
Thank you for creating this free, open source image editor for VSCode!

I'm on Windows 10, and having just installed Luna Paint into VSCode when I run the New Icon command (via the command palette) it asks me for the width & height ( I go with the default 256x256) and then I get the following error:

![image](https://user-images.githubusercontent.com/551619/142380761-6861693e-c71f-4031-8244-979cc512b51e.png)

This seems not great so I figured I'd let y'all know.

I confirmed that the directory does exist.  
It's weird that the error message is talking about a relative path but the listed path is absolute (starts with C:\).

**Comment by Tyriar** [comment]
Hmm I've never seen this and can't reproduce, can you give some more details about what type of window you're running this in? A [gif](https://gifcap.dev/) of the whole window with the explorer showing would probably give me enough information.

**Comment by Tyriar** [comment]
Oh I can reproduce, it happens when opening in a window without a folder opened.

**Comment by onmax** [comment]
> Oh I can reproduce, it happens when opening in a window without a folder opened.

It happens the same to me, but trying to create an image instead of an icon

**Comment by Tyriar** [comment]
Looks like this is a regression in VS Code, will report soon

**Comment by Tyriar** [comment]
Reported to https://github.com/microsoft/vscode/issues/137524, nothing to do here after reviewing the code.

**Comment by Tyriar** [comment]
This actually is an issue with a misuse of `Uri.parse`, reopening
