### ISSUE TITLE
New File... options do nothing if no folder is open

### ISSUE THREAD

**Issue by gjsjohnmurray** [lunapaint/vscode-luna-paint#108]
Issue Type: <b>Bug</b>

1. Launch VS Code with Luna Paint installed.
2. If a folder or a workspace is open, close it.
3. Use 'New File...' from the File menu or from Get Started page.
4. Choose either of the Luna Paint entries.
5. Provide the dimensions when prompted.

:bug: no untitled file gets created.

6. Open a folder, then repeat steps 3 to 5. A file gets created.

Extension version: 0.10.0
VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Tyriar** [comment]
Thanks, looks like it's the same as https://github.com/lunapaint/vscode-luna-paint/issues/107as I'm able to reproduce that in an empty workspace.

**Comment by gjsjohnmurray** [comment]
I had wondered if mine was a dup of this, but I don't get the alert.

**Comment by Tyriar** [comment]
Guessing the getting started page swallows the error
