### ISSUE TITLE
Compress PNG (all caps) fails

### ISSUE THREAD

**Issue by kfasick** [lunapaint/vscode-luna-paint#109]
Issue Type: <b>Bug</b>

1) Save a png file with extension .PNG in caps 2) Right click in Explorer, compress image 3) Observe error ..."image.PNG" file has an incorrect file extension. It is actually a mime type of image/png!" 4) Rename to lowercase extension and try again 5) Observe success message "reduced by" percent.

Extension version: 0.11.0
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

**Comment by Tyriar** [comment]
Is this Windows explorer or VS Code's explorer? "Compress image" isn't a feature of Luna Paint?

**Comment by kfasick** [comment]
Sorry wrong context. VS Code Explorer.

Sent from my Windows 10 device

**Comment by kfasick** [comment]
Sorry wrong context. This was from VS Code Explorer, not Luna Paint.
