### ISSUE TITLE
Saving the image truncates the history!

### ISSUE THREAD

**Issue by MonkeyNinja** [lunapaint/vscode-luna-paint#110]
Issue Type: <b>Bug</b>

As Title... :-(

**Comment by Tyriar** [comment]
I can't reproduce this, probably some edge case I'm not covering correctly. Can you record a gif of this happening with https://gifcap.dev/ ?

**Comment by Tyriar** [comment]
Also, you might be seeing https://github.com/lunapaint/vscode-luna-paint/issues/24?

**Comment by Tyriar** [comment]
Need some more information to be able to action this so closing off
