### ISSUE TITLE
Doesn't support fingers )

### ISSUE THREAD

**Issue by nZeus** [lunapaint/vscode-luna-paint#112]
Issue Type: <b>Bug</b>

Doesn't work with touch screens, Cannot draw anything with fingers

1. Open png file
2. Select "Pencil" tool
3. try to draw a line

Expected: you can draw with fingers
Actual: it starts drawing, but after a short move it stops. If you then move cursor with touchpad, it seems like the "left" mouse button is pressed, and continues drawing. There is no way to stop drawing, only option is to close the file 

Extension version: 0.11.0
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (12.80GB free)|
|Process Argv|--crash-reporter-id d9016d7c-36c1-4509-b18f-69510e4a865d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by Tyriar** [comment]
Thanks for the report, I don't have a touch device but I see something weird going when I emulate touch events so I'll have a look at that.
