### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Heath123** [lunapaint/vscode-luna-paint#114]
There seems to be no source code in the repo, and the license says All Rights Reserved - is this extension closed source? If so, are there any plans to open source it?

**Comment by Tyriar** [comment]
Yes, the extension is closed source right now. I've considered opening it up, but don't think it will happen in the foreseeable future. My main reasoning being:

- I don't want some big corp to take what is likely around 1000 hours of effort I've put into this project, close it, sell it and build on it faster than I can.
- I want the flexibility to do what I want with it in the future, if I opened it under AGPL for example to combat the above it would restrict if I were to try monetize it. FWIW regarding monetization, if I ever do go down that route I've committed to myself that anything that I have released already will remain free.
- Running an open source project is stressful and I get a lot of that already in my professional life, right now this project helps reduce my stress and it would be very disappointing if it went the other way.

**Comment by Heath123** [comment]
I think that's a shame, because this seems like a decent cross-platform Paint.NET rival that could be a great community project and maybe be standalone at some point, and I would like to try to contribute to this.
Obviously it's entirely your choice but I think maybe I can address some of those problems:

- Corporations doing things like that for small projects seems quite rare, but you could license under something that disallows commercial use or that requires them to share source.
- As far as I know, if you write code it's your code, and you are allowed to freely relicense it. Getting permission from external contributors might be a problem but I guess you could have some kind of agreement where all the code belongs to you and you're allowed to relicense it.
- I don't think managing an open source project is necessarily more stressful than a closed source one, I guess if you're accepting contributions it means you have to do code review but then again it means you're not under pressure to single-handedly implement every single feature for every use case that anyone has because people can just add the things they need.

If existing licenses don't fit your needs you can always write your own, so I think open sourcing this is still something you should consider.

**Comment by Tyriar** [comment]
I'm definitely still considering it, just once it's done it can never be undone. Or if you try, a subsection of the community will hate you like has happened in some other projects that decided to go closed or use more restrictive licences.

Just want to keep my options open for now.

Thanks for the feedback 🙂

**Comment by elazarcoh** [comment]
Hi @Tyriar,
I have an [Extension](https://github.com/elazarcoh/simply-view-image-for-python-debugging) that lets you view images during Python debug, and I was thinking about improving the image viewer with some features that which I'll need to write my own viewer, which I tried but without much success. The learning-curve too steep to get something work in the limited time I have to develop it, using the method I tried (threejs). I hoped to get some help from luna-paint source code as a reference. I would really appreciate if you can help me with one of the following:
1. Part of the source code just to make an image viewer with zooming and panning features. I need the ability to add the grid lines luna-paint has when zooming-in for example, so using base html components won't work for me.
2. Direct me to your approach to get it running (html canvas? webgl? maybe some library?)

The features that I'll add up eventually are:
* Grid lines when zoomed in
* Pixel value shown on each pixel when zoomed in
* Pixel value shown on hover (tooltip/bottom-bar)
* Probably some contrast-enhancement 

I think that luna-paint is exactly what I need for reference, but I understand your point of not wanting to share the full source code.
I hope this isn't too much to ask, maybe what I'm asking is exactly the kind of thing that you don't want to share, and I would understand it. You can answer to me by mail if you like: elazarcoh@gmail.com.
Thanks,
Elazar

**Comment by Tyriar** [comment]
@elazarcoh luna paint uses raw webgl which I would not recommend unless you already know how it works. A 2d canvas context would be the most approachable way of drawing some grid lines

**Comment by elazarcoh** [comment]
@Tyriar Thanks. I find 2d canvas too inconvenient to implement the required features. Instead, I got into learning webgl. Thanks anyway.
