### ISSUE TITLE
father@ULGK

### ISSUE THREAD

**Issue by FatherofUniverseLordGodKing** [lunapaint/vscode-luna-paint#115]
ADD ISSUE DESCRIPTION HERE

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
Embedder: vscode.dev

Extension version: 0.11.0

**Comment by Tyriar** [comment]
Assuming this was an accident.
