### ISSUE TITLE
Hex color box doesn't allow paste or lowercase

### ISSUE THREAD

**Issue by JacksonKearl** [lunapaint/vscode-luna-paint#127]
Issue Type: <b>Bug</b>

As above, I can't paste a value into hex color entry area, and it seems to error out if I enter lowercase letters.

Extension version: 0.12.0
VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id fb23c17b-00e5-48cc-860e-4c9767e35c1d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
wslgetstarted:30426333
vscop804:30404766
vscop341:30404997
vsrem710:30416614
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by Tyriar** [comment]
Pasting seems like a mac-specific problem. Can you elaborate on the lowercase error?

**Comment by JacksonKearl** [comment]
No longer seeing the lowercase issue, not sure what was going on
