### ISSUE TITLE
Editor association with *.{png} has no effect

### ISSUE THREAD

**Issue by carstenschwede** [lunapaint/vscode-luna-paint#129]
Thanks for a great extension, it works well with .jpegs, however I can't get it to open .png files as well, despite adding

```json
    "workbench.editorAssociations": {
        "*.{bmp,ico,jpg,jpeg,png}": "luna.editor"
  }
```

to the settings. Is there any other place where I have to assign luna.editor to open .png files?

VSCode Version: 1.63.2 on macOS 12.1
Luna Paint Version: 0.12.0

**Comment by carstenschwede** [comment]
Interesting, using this

```
  "workbench.editorAssociations": {
        "*.png": "luna.editor",
        "*.bmp": "luna.editor",
        "*.jpeg": "luna.editor",
        "*.jpg": "luna.editor",
        "*.ico": "luna.editor"
    }
```

works for all mentioned filetypes (including pngs).

But this doesn't work for pngs (but does for jpegs)?

```
"workbench.editorAssociations": {
        "*.{bmp,ico,jpg,jpeg,png}": "luna.editor"
  }
```

**Comment by Tyriar** [comment]
That's odd, this is what I have right now which works fine:

```json
  "workbench.editorAssociations": {
    "*.{bmp,ico,jpg,jpeg,png}": "luna.editor",
    "*.webp": "luna.editor",
    "*.jpe": "luna.editor",
    "*.ipynb": "jupyter-notebook"
  },
```

I'm guessing this is a problem in VS Code, not the extension. @lramos15 any idea what could be causing this?

**Comment by carstenschwede** [comment]
I happened to have a conflicting entry in my user settings, which for some reason won't get replaced if I use the `*.{png}` pattern in my workspace settings:

User `settings.json`:

```
	"workbench.editorAssociations": {
		"*.png": "imagePreview.previewEditor"
	}
```

Workspace `.vscode/settings.json` which does not work:

```
    "workbench.editorAssociations": {
        "*.{png}": "luna.editor"
    }
```

Workspace `.vscode/settings.json` which does work:
```
    "workbench.editorAssociations": {
        "*.png": "luna.editor"
    }
```

Not sure why the culy bracket glob pattern does not work. I removed `workbench.editorAssociations` from both (user + workspace) settings and it now works without specifying any associations explicitly.

**Comment by Tyriar** [comment]
Thanks for the extra info, I moved this over to the VS Code repo: https://github.com/microsoft/vscode/issues/141286
