### ISSUE TITLE
Diff mode?

### ISSUE THREAD

**Issue by KillyMXI** [lunapaint/vscode-luna-paint#132]
I have Luna paint as the editor associated with PNG files.

Now when I change an image file and then select it in the Source Control panel, VSCode opens two full image editors, which is a bit slow and also cluttered with unnecessary for that situation UI elements.

(The same effect can be observed when selected two images and chosen "Compare Selected" from context menu.)

If taken this further, I think diff view for images could provide different set of useful features to highlight the changes.

But first of all I wonder whether it is possible to detect the way how the editor was opened and show the reduced view when full editor is not required.

**Comment by Tyriar** [comment]
Ideally I'd like to show a single editor with multiple presentations similar to how github.com does it (onion skin, slider, side-by-side, etc.). I don't think extensions can control this at all until API is added to VS Code though in https://github.com/microsoft/vscode/issues/138525

One small improvement I might be able to make is to hide all the UI windows initially when an image is opened in readonly mode.

**Comment by Tyriar** [comment]
Made the change to hide the UI in readonly images which is a little better. Unfortunately the right editor is just opened as a regular editor AFAICT so it would be a bit of a hack to try to hide the UI there.

![image](https://user-images.githubusercontent.com/2193314/154807687-a3afda06-57c5-452a-9114-c79e5fcd1709.png)

Going to close this out for now but I've subscribed to https://github.com/microsoft/vscode/issues/138525 in case that ends up happening.

**Comment by KillyMXI** [comment]
Another minor convenience might be a command and an icon at the top right that can toggle all panels visibility.
Something like "Temporarily hide all windows".
This can be handy in the diff view or even in regular editor when parts on the image are hidden behind panels or one want to reduce the clutter temporarily.

**Comment by Tyriar** [comment]
I've been trying to keep the buttons in the UI as minimal as possible to keep in the spirit of VS Code. There's actually a shortcut for this by hitting F5, F6, F7 and F8 (same as Paint.net).

**Comment by Tyriar** [comment]
I'm hopeful that custom editors will eventually get more control over diff editors in which case the extension could have a single readonly editor with custom controls which would be much nicer

**Comment by zjffun** [comment]
Here seems a solution https://github.com/microsoft/vscode/issues/138525#issuecomment-1847679100 .
