### ISSUE TITLE
Content Security Policy blocks Luna-paint in vscode.dev

### ISSUE THREAD

**Issue by dragobit** [lunapaint/vscode-luna-paint#133]
VScode version: vscode.dev
OS :Debian Vivaldi 89.0.4389.128(32-bit)

![screenshot](https://user-images.githubusercontent.com/97995130/155630388-a0f4a80a-c833-40fa-8963-521a1642332f.jpg)

I can't open images using Luna-paint.

**Comment by Tyriar** [comment]
Weird, works for me on Windows/Edge🤔 

![image](https://user-images.githubusercontent.com/2193314/155637775-333e2ff1-d993-4c71-a38d-933e51b831b5.png)

That 89 looks like it's probably the backing Chromium version of Vivaldi and if so that is probably the cause considering my Edge is up to 100.

**Comment by Tyriar** [comment]
Closing as it's working on newer versions of Chromium

**Comment by dragobit** [comment]
On this version of Vivaldi, other vscode extensitions can't work either.
So, my issue is not due to LunaPaint.

Thank you for your support,Tyriar!

**Comment by Tyriar** [comment]
Thanks for confirming 👍
