### ISSUE TITLE
Defaut obtrusive dark backgroud

### ISSUE THREAD

**Issue by Xenon4416** [lunapaint/vscode-luna-paint#134]
Issue Type: <b>Bug</b>

just opening an image open with a dark background that obstructs image view
![image](https://user-images.githubusercontent.com/35037446/155655479-51994ea7-c020-43d3-a46e-928341fa4f42.png)

Extension version: 0.13.2
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.4.0-100-generic
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|11.35GB (0.61GB free)|
|Process Argv|--unity-launch --crash-reporter-id a3f9efc0-e3e7-40c8-aad7-61223153f16f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|

</details>

**Comment by Tyriar** [comment]
That's weird, the background is meant to be there but it's only meant to be on the outside of the image, covering up the checked pattern. Does this fix itself if you resize the window?

**Comment by Xenon4416** [comment]
no it doesn't. moreover when i move or change the zoom of the image, the black background crops the view of the actual image as seen in the above screenshot. the bottom part of the image is blocked there.

**Comment by Tyriar** [comment]
If you open dev tools via the help menu do any errors show up in the console?

**Comment by Tyriar** [comment]
Since I haven't seen this anywhere else my guess is graphics driver issues on Linux as I have to deal with similar things in VS Code's terminal. Fortunately the terminal has a fallback CPU-based renderer you can always switch to but not with Luna Paint as I felt that kind of defeated a big part of why the extension was good and didn't want to waste time on a slow renderer.

**Comment by Xenon4416** [comment]
i'm on intel integrated graphics so is it related to integrated graphics or issues based on graphics drivers, if it is driver issues then what may be the recommended one?

**Comment by Tyriar** [comment]
I'm not sure, but the fact it only happens on Linux is a pretty sure clue that it's a graphics problem, whether that be in Chromium/Electron or OS/drivers.

**Comment by Tyriar** [comment]
Closing off as I suspect it's webgl issues in the OS or Chromium and beyond my ability to fix
