### ISSUE TITLE
Don't open an image immediately in the edit mode

### ISSUE THREAD

**Issue by MatejBransky** [lunapaint/vscode-luna-paint#136]
Hi, thanks for your extension but I don't know how to use it for simple browsing because I don't want to edit an image immediately. I would like to do it maybe later but before that I need to browse which I want to edit and with immediately enabled edit mode a lot of panels are there which hides huge parts of the image so it's easier for me to open this image in a file explorer, to see it there and then maybe go back to VS Code to edit it and that's just annoying.

Or is it possible to use it with some other extension which just shows images and then open it in this extension?

Thank you for your response.

**Comment by Tyriar** [comment]
It sounds like you're the type of user that would want to keep the default image preview extension as the default and then reopen the image with. VS Code may at some point allow an edit button to be added to the image preview (https://github.com/microsoft/vscode/issues/116120), but for now the way to do this would be to clear out `luna.editor` from your `workbench.editorAssociations` setting, opening an image should then show this:

![image](https://user-images.githubusercontent.com/2193314/159923213-7279ceab-258e-4b6d-9efd-e7f9c0843182.png)

Select configure and then Image Preview:

![image](https://user-images.githubusercontent.com/2193314/159923267-594441d6-5e21-48a8-9338-371389b2b83a.png)

Images should now open in the image preview and to "upgrade" to Luna Paint you would need to run the `View: Reopen Editor With` command. If this is a common thing you could also create a custom keybinding for `workbench.action.reopenWithEditor` like this:

```json
{
  "key": "ctrl+k b",
  "command": "workbench.action.reopenWithEditor"
}
```

**Comment by MatejBransky** [comment]
That's a clever solution! Thank you. 🙂

**Comment by Tyriar** [comment]
Will reopen to track adding this to https://github.com/lunapaint/vscode-luna-paint/wiki/Customization as it's not very obvious 🙂

**Comment by Tyriar** [comment]
Added https://github.com/lunapaint/vscode-luna-paint/wiki/Customization,

**Comment by enricodias** [comment]
The popup asking to keep Luna as the default will show only once. After that, even if you didn't pick any option Luna will keep being the default even without any `workbench.editorAssociations` setting present.

Restarting vscode or reinstalling the extension didn't work.

**Comment by Tyriar** [comment]
@enricodias if that's so it's a bug in VS Code, could you report to https://github.com/microsoft/vscode/issues?
