### ISSUE TITLE
Error: Assertion failure

### ISSUE THREAD

**Issue by OlagStegan** [lunapaint/vscode-luna-paint#137]
Issue Type: <b>Bug</b>

On opening a file get an error message "Assertion failure: 20617 !== 0"

Extension version: 0.13.2
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.88GB free)|
|Process Argv|--crash-reporter-id 8cf13605-3740-4498-b970-4545d4b0c3b0|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
Would you be able to upload this file? Either to github or to my email (`<myusername>@<myusername>.com`)

**Comment by OlagStegan** [comment]
Sorry about the delay I'll try to email it

**Comment by Tyriar** [comment]
@OlagStegan I had a look at this file, it's actually a PNG and Luna Paint doesn't yet have detection of mismatched file extensions. It should work when renamed to end with `.png`. I created https://github.com/lunapaint/vscode-luna-paint/issues/139 to track this feature which would allow opening the file with warnings.

**Comment by Tyriar** [comment]
I improved the error message in the meantime until #139 is done:

<img width="395" alt="Screen Shot 2022-04-24 at 8 52 33 am" src="https://user-images.githubusercontent.com/2193314/164984960-0f86f820-0df9-4dff-824f-35c0e9829299.png">
