### ISSUE TITLE
Question: How can I use default image viewer of vscode to view my image, instead of using Luna to edit it?

### ISSUE THREAD

**Issue by stone926** [lunapaint/vscode-luna-paint#138]
How can I use default image viewer of vscode to view my image, instead of using Luna to edit it? After installing Luna, vscode use Luna to display the image every time, but I often just need the default viewer to have a look, so what should I do to change the default image viewer? Thanks a lot.

**Comment by Tyriar** [comment]
See https://github.com/lunapaint/vscode-luna-paint/issues/136
