### ISSUE TITLE
Error: "WebGL2 is not supported" on Linux

### ISSUE THREAD

**Issue by luanpiegas** [lunapaint/vscode-luna-paint#146]
I'm using Zorin OS 16 (Ubuntu based), and when I tried to open any image this message appears:
![Screenshot from 2022-07-08 18-14-58](https://user-images.githubusercontent.com/4358071/178071556-a092ee0c-d58f-45ea-bb80-a3af7fad2a47.png)

**Comment by Tyriar** [comment]
Modern VS Code does support webgl2, it looks like you might be running with `code --disable-gpu` or have an incompatible distro/system. Unfortunately is webgl2 isn't available then Luna Paint won't work.
