### ISSUE TITLE
No Text Input

### ISSUE THREAD

**Issue by SummittDweller** [lunapaint/vscode-luna-paint#147]
I'm using this wonderful extension on two different Mac computers and in both cases when I select the Text input tool I can draw a text box that's populated with "Lorem ipsum", but I'm unable to change that text, presumably because there is no pop-up editing window like the one I saw at the 1:10 mark in https://www.youtube.com/watch?v=UMqwTfrbqxs.

**Comment by Tyriar** [comment]
I just tested the latest version on my mac and double click is working 🤔 

Could you open devtools (Help > Toggle Developer Tools), go to the console and see if there are any logs when you draw the text and double click?

**Comment by SummittDweller** [comment]
body {
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	padding:1em;
	margin:auto;
	background:#fefefe;
}

h1, h2, h3, h4, h5, h6 {
	font-weight: bold;
}

h1 {
	color: #000000;
	font-size: 28pt;
}

h2 {
	border-bottom: 1px solid #CCCCCC;
	color: #000000;
	font-size: 24px;
}

h3 {
	font-size: 18px;
}

h4 {
	font-size: 16px;
}

h5 {
	font-size: 14px;
}

h6 {
	color: #777777;
	background-color: inherit;
	font-size: 14px;
}

hr {
	height: 0.2em;
	border: 0;
	color: #CCCCCC;
	background-color: #CCCCCC;
    display: inherit;
}

p, blockquote, ul, ol, dl, li, table, pre {
	margin: 15px 0;
}

a, a:visited {
	color: #4183C4;
	background-color: inherit;
	text-decoration: none;
}

#message {
	border-radius: 6px;
	border: 1px solid #ccc;
	display:block;
	width:100%;
	height:60px;
	margin:6px 0px;
}

button, #ws {
	font-size: 12 pt;
	padding: 4px 6px;
	border-radius: 5px;
	border: 1px solid #bbb;
	background-color: #eee;
}

code, pre, #ws, #message {
	font-family: Monaco;
	font-size: 10pt;
	border-radius: 3px;
	background-color: #F8F8F8;
	color: inherit;
}

code {
	border: 1px solid #EAEAEA;
	margin: 0 2px;
	padding: 0 5px;
}

pre {
	border: 1px solid #CCCCCC;
	overflow: auto;
	padding: 4px 8px;
}

pre > code {
	border: 0;
	margin: 0;
	padding: 0;
}

#ws { background-color: #f8f8f8; }


.bloop_markdown table {
border-collapse: collapse;  
font-family: Helvetica, arial, freesans, clean, sans-serif;  
color: rgb(51, 51, 51);  
font-size: 15px; line-height: 25px;
padding: 0; }

.bloop_markdown table tr {
border-top: 1px solid #cccccc;
background-color: white;
margin: 0;
padding: 0; }
     
.bloop_markdown table tr:nth-child(2n) {
background-color: #f8f8f8; }

.bloop_markdown table tr th {
font-weight: bold;
border: 1px solid #cccccc;
margin: 0;
padding: 6px 13px; }

.bloop_markdown table tr td {
border: 1px solid #cccccc;
margin: 0;
padding: 6px 13px; }

.bloop_markdown table tr th :first-child, table tr td :first-child {
margin-top: 0; }

.bloop_markdown table tr th :last-child, table tr td :last-child {
margin-bottom: 0; }

.bloop_markdown blockquote{
  border-left: 4px solid #dddddd;
  padding: 0 15px;
  color: #777777; }
  blockquote > :first-child {
    margin-top: 0; }
  blockquote > :last-child {
    margin-bottom: 0; }

code, pre, #ws, #message {
    word-break: normal;
    word-wrap: normal;
}

hr {
    display: inherit;
}

.bloop_markdown :first-child {
    -webkit-margin-before: 0;
}

code, pre, #ws, #message {
    font-family: Menlo, Consolas, Liberation Mono, Courier, monospace;
}


.send { color:#77bb77; }
.server { color:#7799bb; }
.error { color:#AA0000; }Thanks for the quick reply, Daniel.

I’m seeing this error in the console just after double-clicking the text box…

  ERR Error: Cannot back up in this state: Could not backup file as it's too large
    at Js.backup (mainThreadCustomEditors.ts:720:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async workingCopyBackupTracker.ts:188:21


I tried it with a couple of different images but am getting the same thing for each. Looking for a smaller image, or maybe I’ll try with a new/blank image next.

-Mark M.

body{font-family:Helvetica,Arial;font-size:18px}   On July 19, 2022 at 4:04:36 PM, Daniel Imms ***@***.***) wrote: 

I just tested the latest version on my mac and double click is working 🤔

Could you open devtools (Help > Toggle Developer Tools), go to the console and see if there are any logs when you draw the text and double click?

**Comment by SummittDweller** [comment]
OK, I think I have this solved...  my double-click speed was set to "full" so apparently I wasn't able to click it fast enough?  I followed guidance from https://mcmw.abilitynet.org.uk/how-to-slow-down-the-mouse-and-trackpad-double-click-speed-in-macos-12-monterey and now the text input box appears as it should.  Sorry for the trouble.  Hope this issue post might help if others run into the same issue.

I believe this can be closed as resolved.  Take care.

**Comment by Tyriar** [comment]
Interesting glad to hear your figured it out 👍 That logged error is expected currently
