### ISSUE TITLE
Support saving TGA to uncompressed RGBA format

### ISSUE THREAD

**Issue by dirondin** [lunapaint/vscode-luna-paint#155]
Luna saves TGA in "Runlength encoded color-mapped images" (across specification http://www.paulbourke.net/dataformats/tga/, section "Data Type field").
Some editors don't support this format fully.
For example:
- Affinity Photo ruins colours
- Mac OS viewer sometimes can't open file at all (if tga contains alpha channel)

Can you add to Luna dialog with variations of saving format (for TGA usually it includes selecting RLE compression and origin)? For me very important "Uncompressed, RGB images".

<img width="1024" alt="screenshot" src="https://user-images.githubusercontent.com/8371890/188831777-1b4f0184-d48a-4070-a375-e8a45b776a88.png">

[test.tga.zip](https://github.com/lunapaint/vscode-luna-paint/files/9504286/test.tga.zip)

Saving TGA dialog in GIMP for example:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/8371890/188832581-eec61207-3c57-4b38-b823-5be3b4536af3.png">

**Comment by Tyriar** [comment]
Related: https://github.com/lunapaint/vscode-luna-paint/issues/69, https://github.com/lunapaint/vscode-luna-paint/issues/156
