### ISSUE TITLE
Luna VS clipboard 

### ISSUE THREAD

**Issue by mit-net-ai** [lunapaint/vscode-luna-paint#159]
ADD ISSUE DESCRIPTION HERE

Version: 1.72.3
Commit: f69482e92e41b84fb15688f3c0d0a1eca1d5bce3
User Agent: Mozilla/5.0 (Linux; Android 11; KFQUWI) AppleWebKit/537.36 (KHTML, like Gecko) Silk/104.2.16 like Chrome/104.0.5112.114 Safari/537.36
Embedder: github.dev

Extension version: 0.16.0

**Comment by mit-net-ai** [comment]
Exploring on a tablet

**Comment by Tyriar** [comment]
Not sure what you mean here?
