### ISSUE TITLE
Luna Paint as a "Language Mode" in VSCode?

### ISSUE THREAD

**Issue by Identifier** [lunapaint/vscode-luna-paint#165]
There's an extension in VS Code that allows you to open Zip files in the pane Explorer pane and navigate/open their files: https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-zipexplorer

With that extension, you don't need to extract the files to open them.  You can just single-click on files within Zip to select them and see a tab open with their contents, just the same as other normal files in Explorer pane, and they open up a new tab.

Anyway, this all works great with text/code files, but for .png files it opens them up in Binary view instead of in Luna Paint.  I tried clicking in the bottom-right of VSCode's status bar to change the Language Mode from "Plain Text" to "Luna Paint", but I couldn't find "Luna Paint" in the list.  Apparently Luna isn't available as a "Language Mode".

If you could expose Luna Paint as a "Language Mode" it would be great integration!

**Comment by Tyriar** [comment]
It's an issue of "custom editor" vs the "language mode of a text editor". I considered what you're asking and think I discussed it with the VS Code team at some point and I don't think it will happen. The current recommendation is to run the reopen in editor command which is explained a bit in https://github.com/lunapaint/vscode-luna-paint/wiki/Customization#dont-open-in-edit-mode-by-default
