### ISSUE TITLE
Feature requiremnt

### ISSUE THREAD

**Issue by zillionare** [lunapaint/vscode-luna-paint#172]
This is a great tool. None of tools can compare on mac. However, I need "make background transparent" feature, would you please provide?

**Comment by zillionare** [comment]
just as same as https://www2.lunapic.com/editor/?action=transparent

**Comment by Tyriar** [comment]
Ah I see, I think you want https://github.com/lunapaint/vscode-luna-paint/issues/93 then; to be able to select a portion of the image with a threshold, similar to fill but using the selection.
