### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by wrgrant** [lunapaint/vscode-luna-paint#187]
Wondering about project status.

This is an awesome extension for making simple edits right in VSCode.

Is there any plan to open source so the community could help develop?

**Comment by Tyriar** [comment]
Glad you're liking the extension! I had a think about open sourcing again and my feelings as still pretty much the same as I explained previously in https://github.com/lunapaint/vscode-luna-paint/issues/114. 

As for the project status, I was just taking a break from it for a bit and absolutely plan on ramping back up when the motivation hits me.
