### ISSUE TITLE
Luna Paint fails to save PNG

### ISSUE THREAD

**Issue by CodaKidGit** [lunapaint/vscode-luna-paint#194]
Issue:
Sometimes when a user tries to save their .png image after editing it, Luna Paint won't save the image. No errors appear on screen, but the unsaved circle never goes away even after using the shortcut to save, click File > Save, or even File > Save All. Java Files open in the same workspace save correctly.

Steps to Reproduce:
1. Open a .png file in Luna Paint.
2. Make it messy. Unfortunately, I am not sure at this time what exactly causes the issue. I can't seem to reproduce myself, but I have seen it many times on other student's computers.
3. Attempt to save. Nothing will happen upon hitting the save button.

Let me know if there is any more information I can try to grab you next time I see the issue.

**Comment by Mqxx** [comment]
I had the same problem that I needed to hit the save button 2 times in a row to get the image saved. This problem also happens in the draw.io extension. I am not sure maybe it is one of the vs code APIs that causes this.

**Comment by Tyriar** [comment]
FYI @mjbvz, I've seen this reported a few times in this repo and on twitter. Likely an issue with custom editors. cc @tyaginidhi

**Comment by tyaginidhi** [comment]
This is similar to the issue I have noticed - though in our case its consistent - we do not get call to our fileSystemProvider writeFile call for the save flow to be triggered: https://github.com/lunapaint/vscode-luna-paint/issues/192

**Comment by Tyriar** [comment]
Thanks @tyaginidhi, closing this off in favor of the internal tracking issue. Hopefully it'll get fixed soon
