### ISSUE TITLE
Feature Suggestion: make a menu to change size of pencil

### ISSUE THREAD

**Issue by Simsiano** [lunapaint/vscode-luna-paint#205]
Type: <b>Feature Request</b>

Hi, the program is great but I think you should add a feature that makes you able to change the size of the pencil,

**Comment by Tyriar** [comment]
duplicate of https://github.com/lunapaint/vscode-luna-paint/issues/20

**Comment by Simsiano** [comment]
Just to ask, but where is the option?

**Comment by Tyriar** [comment]
@Simsiano your ask is basically the same as #20 to create a brush tool which was going to be essentially a more powerful pencil and pencil would remain as single pixel with no AA logic.
