### ISSUE TITLE
New_rebo

### ISSUE THREAD

**Issue by danielCalbonero12345** [lunapaint/vscode-luna-paint#216]

**Comment by ccarreiro** [comment]
![Screenshot_20240630-230001](https://github.com/lunapaint/vscode-luna-paint/assets/34811379/600b6f0c-093f-4a0c-829c-63d050e76d0b)
![Screenshot_20240630-225947](https://github.com/lunapaint/vscode-luna-paint/assets/34811379/e398b90c-d93d-448d-be36-dac107890c9d)

**Comment by ccarreiro** [comment]
Tudo À Vista
