### ISSUE TITLE
add more shapes besides rectangles?

### ISSUE THREAD

**Issue by scaevitas** [lunapaint/vscode-luna-paint#31]

**Comment by Tyriar** [comment]
👍 will probably add line and circle next and then look into more interesting shapes. I want to make sure the way that the shapes works (finishing shape, handles, etc.) is really solid before adding too much to it.

**Comment by Tyriar** [comment]
Line is done in 0.5

**Comment by Tyriar** [comment]
Closing this off as there is now line, ellipse and 2 triangles. I plan on adding more over time
