### ISSUE TITLE
Unable to save image?

### ISSUE THREAD

**Issue by JacksonKearl** [lunapaint/vscode-luna-paint#33]
I have a simple image I'm trying to add a rectangle to, save seems to work fine but then I reopen the image and the changes are gone. This is the console log:

![image](https://user-images.githubusercontent.com/8586769/110847370-b381d100-8261-11eb-8e49-b82c94fcad48.png)

**Comment by Tyriar** [comment]
😕 haven't seen that before. This could be an issue in VS Code Insiders maybe? I think keybindings might be a little broken in Insiders right now too.
