### ISSUE TITLE
Weird behavior when creating a new image

### ISSUE THREAD

**Issue by JacksonKearl** [lunapaint/vscode-luna-paint#34]
1. New file, named `whatever.png`
2. Luna opens up, but there's no image.
2. Click the 0x0 in the in-editor status bar, prompts for height and width
3. Get this prompt, which doesn't really make sense in this context
![image](https://user-images.githubusercontent.com/8586769/110973994-d9b37980-8312-11eb-840b-58388bb3b469.png)
4. Upon clicking either of the options, nothing seems to happen. Image is still 0x0.

I'd expect the case of creating a brand new file in explorer to open up luna and immediately prompt me for height/width, then not prompt for rescaling mode.

**Comment by Tyriar** [comment]
I was thinking about implementing this but thought it was just error out and that's the expected behavior. Maybe I can special case an empty file like this to act similar to New Image.

**Comment by Tyriar** [comment]
Did one better I think and pulled the dimensions from `luna.defaultImageSize`
