### ISSUE TITLE
Saving an unchanged file causes change on disk

### ISSUE THREAD

**Issue by lramos15** [lunapaint/vscode-luna-paint#36]
1. Open an image in luna paint
2. Save it right after opening
3. 🐛 SCM view says the file has changed on disk

What's expected is that nothing happens since the file is not dirty.

**Comment by Tyriar** [comment]
What's happening is it's just saving it again with different encoding that it originally used so the bits end up different. I think you're right and I'll just block that from happening for non-dirty images.

**Comment by lramos15** [comment]
Is there a specific reason the encoding is changing? I would expect Luna paint to try to preserve the encoding but I also don't know if changing it is a requirement to allow editing.

**Comment by Tyriar** [comment]
@lramos15 currently there are no encoding options, Chromium handles all the saving. I'm just starting to get into that now with .ico (which is a container for .png and .bmp).
