### ISSUE TITLE
Allow for quick creation of image based on clipboard image

### ISSUE THREAD

**Issue by misolori** [lunapaint/vscode-luna-paint#40]
Often times I am working in a design tool and have a screenshot or an image on my clipboard (here's my clipboard images via Alfred):

![image](https://user-images.githubusercontent.com/35271042/113785709-869fcd00-96ec-11eb-9bad-20cc54b57418.png)

They all vary in sizes. It would be great to have a command that would like "Create new file from clipboard" and it would detect the sizes automatically and paste it into the canvas.

Photoshop detects when there's an image and has this as the default when creating a new image:
![image](https://user-images.githubusercontent.com/35271042/113785986-15ace500-96ed-11eb-93cc-1055da3e10f4.png)

**Comment by Tyriar** [comment]
I use this as a workaround as it's my most common action:

```json
{ "key": "cmd+'",            "command": "luna.file.new", "args": { "width": 1680, "height": 1050 }, "when": "isMac" },
```

I definitely want to add a command that just creates and pastes for me though 👍
