### ISSUE TITLE
Doesn't load images when using Remote WSL.

### ISSUE THREAD

**Issue by Dzejkop** [lunapaint/vscode-luna-paint#44]
I'm trying to open some `.png` files is a WSL session. It looks like the extension is stuck on loading. 

Also when I try running the `New Image` command I'm getting an error `Command 'Luna: File > New Image' resulted in an error (command 'luna.file.new' not found)`

**Comment by Tyriar** [comment]
Something appears to have broken 🙁, I see this in the console:

```
Activating extension 'Tyriar.luna-paint' failed: Unexpected token '.'.
```
