### ISSUE TITLE
Weird flickering when resizing editor

### ISSUE THREAD

**Issue by JacksonKearl** [lunapaint/vscode-luna-paint#45]
I had notebook.png open from here: https://github.com/JacksonKearl/vscode-handydandy-notebook, when I resize the editor (by dragging the sidebar border around, for instance), I sometimes see a weird flicker where the image disappears and the entire editor area fills with the transparency checkmark.
![recording (12)](https://user-images.githubusercontent.com/8586769/116360884-3a105480-a7b5-11eb-8d9f-926ea2893e4a.gif)

**Comment by Tyriar** [comment]
I've never seen this, my guess is that the canvas clearing is happening due to the resize and then rerender on next animation frame skips for some reason.

**Comment by lramos15** [comment]
I see something similar, but the whole webview flashes white

**Comment by Tyriar** [comment]
I think this is dependent on hardware and pretty sure I can't do anything about it, it's just the time it takes to render the first frame after resize kills the canvas texture.
