### ISSUE TITLE
Layers window doesn't update when moving layers up/down

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#50]
Moving a layer up or down doesn't update the layers until another layer is selected.

### reproduction steps:
1. open an image
2. create a new layer
3. press the move the new layer down (no visual change)
4. click on the other layer (the layer order updates)

![layer_window_doesnt_update_on_layer_move_up_or_down](https://user-images.githubusercontent.com/13420573/117327808-4d957c80-ae93-11eb-8148-60d778f7c01e.gif)

### screen recording:
The button `Create a new layer` is pressed.
Layer 2 appears above the Background layer.

The button `Move the active layer down` is pressed.
Nothing changes in the layer window.

The Background layer is clicked.
The layer order updates, now Layer 2 is below the Background layer.

Layer 2 is clicked.

The button `Move the active layer up` is pressed.
Nothing changes in the layer window.

The Background layer is clicked.
The layer order updates, now the Background layer is below Layer 2.

### Notes:
It seems to only be an issue with updating the layer order visually.
The layer order seems to have changed behind the scenes.

Because if a new layer is added after moving the active (top) layer down.
Then a new layer is added above the bottom layer (the previous active layer).

Layers:
Layer 2
Background

With the Layer 2 selected:
Pressing the move down layer button
doesn't change anything.

But pressing the new layer button, results in:
Background
Layer 3
Layer 2

### system:
luna 0.5.0
vscode 1.56.0
windows 10 version 2004

**Comment by Tyriar** [comment]
@duianto thanks a bunch for all the reports, you found a couple of nasty issues ❤️
