### ISSUE TITLE
The numbers in: NewImage-(nr) and Layer (nr) only increases

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#51]
The NewImage-(nr) counter continues to increase, even if all NewImage-(nr) images have been closed.

The same thing happens when creating new layers: Layer (nr)

### reproduction steps:
1. create a new image: shift ctrl ' (' = single quote)
2. a new image is created with the name: NewImage-1.png
3. close the image: ctrl w
4. create a new image: shift ctrl '

### observed:
A new image is created with the name: NewImage-2.png

### expected:
Since no other NewImage's are open, start the counter from 1
NewImage-1.png

### notes:
The number in `NewImage-(number)` starts from 1 again when vscode is restarted.

The same issue also occurred in vscode when opening a new untitled-1 file.
But it's been fixed.

Untiled number always increase
https://github.com/microsoft/vscode/issues/65611

2nd "Untitled" file number starts from previously greatest number of created file
https://github.com/microsoft/vscode/issues/66834

The new untitled file number starts from the next available number.
For example if three untitled files are opened:
Untitled-1
Untitled-2
Untitled-3

if the second file is closed, leaving:
Untitled-1
Untitled-3

when a new file is opened:
Untitled-1
Untitled-3
Untitled-2

and when a new file is opened:
Untitled-1
Untitled-3
Untitled-2
Untitled-4

### system:
luna 0.5.0
vscode 1.56.0
windows 10 version 2004

**Comment by Tyriar** [comment]
I like consistency 🙂 should be relatively easy to do too

**Comment by Tyriar** [comment]
Noticed https://github.com/microsoft/vscode/issues/123360 while working on this issue.
