### ISSUE TITLE
Images window covered by Layers window

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#52]
When a new image is created: `shift ctrl '` (' = single quote)
then a Images window appears in the bottom right corner.

![Code_2021-05-06_18-02-13](https://user-images.githubusercontent.com/13420573/117330054-98b08f00-ae95-11eb-818d-ffa1865fdf49.png)

When the layers window (F7) is opened.
Then the images window can be seen behind the layers window.

![Code_2021-05-06_18-01-42](https://user-images.githubusercontent.com/13420573/117330074-9c441600-ae95-11eb-90e1-bda87f1fcf5b.png)

It doesn't seem to be possible to move the Layers window,
nothing happens if one tries to drag the header.

The Layer window has to be closed to be able to access the Images window.

### side note:
I don't know when the Images window buttons are supposed to work.

Only the Create a new image button seems to do anything.
It asks for the width, height and bits per pixel.

But the image doesn't change size.

The initial image was 800x600.
A squiggly line was drawn on the image.

After pressing the create a new image button, and entering:
100 for the width
100 for the height
and 1 bit (the same thing happens with any of the bpp choices)

The squiggly line image remains unchanged.
And there is no new image in the vscode tabs.

### system:
luna 0.5.0
vscode 1.56.0
windows 10 version 2004

**Comment by Tyriar** [comment]
The images window is only meant to be enabled when you're in an .ico file. I can repro this as well, it's a bug that it displays at all instead of layers when you create a new image.
