### ISSUE TITLE
Default foreground color: white, background: black

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#53]
The default colors when opening an existing or new image, are:
foreground: white
background: black

At least when creating a new image, which has a white background.
It's unlikely that one would want to start drawing with a white color.

So it should probably use the colors:
foreground: black
background: white

### system:
luna 0.5.0
vscode 1.56.0
windows 10 version 2004

**Comment by Tyriar** [comment]
Good call 👍
