### ISSUE TITLE
Middle mouse button drag to pan

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#55]
It would be useful to be able to scroll (pan) the image by middle mouse dragging.

It's a little limiting to only be able to scroll in one direction with the mouse wheel by scrolling up and down or with shift held down: left and right.

The minimap does allow for scrolling.
It also allows for zooming in/out, even while dragging the view rectangle.
This is great 😄 

But it requires the mouse to be moved to the minimap, and if one is zoomed in then the view rectangle can become really small.

Middle mouse dragging to scroll seems to be a common behavior in other applications.

For example:
Gimp
Inkscape
and Blender, in the 2d views (even in the text editor), in the 3d views it requires shift to be held down to pan.

If my experience is to limited, and it's more common to scroll up and down with the mouse wheel, and left and right with shift held down.

Then maybe it could be added as an option, to scroll (pan) by middle mouse button dragging.

**Comment by Tyriar** [comment]
I've considered this, I'm still not 100% sure how I want middle click to work in the end. I suppose we could start with this and if different middle click behaviors come later I could add a setting similar to the `terminal.integrated.rightClickBehavior` setting.

**Comment by ChildishGiant** [comment]
With this I'd suggest adding a pan tool (normally using a hand icon) and middle mouse effectively just switches to it while held.

**Comment by Tyriar** [comment]
Looks like gimp and photoshop both have a hand (pan) tool (H), and you can temporarily use it by holding space and dragging

**Comment by Tyriar** [comment]
I ended up going with H and space for temporary tool (new concept), this will keep the middle mouse button open for some other function in the future:

![recording](https://user-images.githubusercontent.com/2193314/119225367-302df880-bab8-11eb-9ffb-855526dcf06e.gif)


You will also be able to configure which key is used for either of these, here are the default keybindings:

```json
{ "key": "h",                     "command": "luna.tool.hand",
                                     "when": "luna:focused && !sideBarFocus && activeCustomEditorId == 'luna.editor' && focusedView == ''" },
{ "key": "space",                 "command": "luna.tool.handUntilRelease",
                                     "when": "luna:focused && !sideBarFocus && activeCustomEditorId == 'luna.editor' && focusedView == ''" },
```
