### ISSUE TITLE
setting: zoom in out with the mouse wheel without a modifier

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#56]
It's more comfortable to zoom in and out without having to hold down ctrl.

Currently the mouse wheel only scrolls the image vertically.
Shift has to be held down to only scroll horizontally.

Both directions can be reached with: ctrl mouse wheel
zoom out
moving the mouse pointer to the target
and zoom in

It's been a while since I installed gimp and inkscape from scratch, so I don't remember if both or only one of them has the same behavior of only scrolling vertically with the mouse wheel and requiring a modifier to scroll horizontally.

But both gimp and inkscape have the ability to change the mouse wheel to zoom in and out without a modifier.

Even if it's more common for people to only want to scroll vertically with the mouse wheel and horizontally when a modifier key is held down.

It could still be useful to have a setting to be able to zoom in and out with the mouse wheel without a modifier.

**Comment by Tyriar** [comment]
Coming in next version `"luna.mouseWheelBehavior": "scroll" | "zoom"`. This will also flip the modifier action so you can still scroll with ctrl.
