### ISSUE TITLE
layer visibility checkbox reversed when toggle is undone

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#60]
The layer visibility checkbox button can be reversed,
when a layer visibility toggle is undone.

### Reproduction steps

- create a new image: `shift ctrl '` (`'` = single quote)
- show the layer window: `f7`
- click on the checkbox on the right side of Background layer to hide it,
the checkerboard pattern behind the Background layer is shown,
and the history window shows an entry called: `Hide Layer`
- undo, either with: `ctrl z`
or by mouse clicking on the previous undo history action: `New Image`

### Observed
The white Background layer became visible (as expected),
but in the layer window, the Background layers visibility checkbox is still unchecked.

Clicking the checkbox hides the layer and it adds a checkmark.

The layer visibility checkbox has been reversed.

It can be restored to the expected behavior by undoing again after toggling the visibility.

### Expected
A layers visibility checkbox should also be undone,
so that it matches the current layers visibility.

### System
luna 0.5.0
vscode 1.56.0
windows 10 version 2004

**Comment by Tyriar** [comment]
@duianto FYI I shipped 0.5.1 with the image window fix (https://github.com/lunapaint/vscode-luna-paint/issues/52)
