### ISSUE TITLE
Could not undo entry "Finish Rectangle"

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#64]
Undo breaks when trying to undo a new layer,
that was added before a rectangle drawing had been finished.

#### Reproduction steps
- select the rectangle tool
- draw a rectangle
- add a new layer
- undo (ctrl z, or click an earlier action in the history window)

#### Expected
The actions should be undone.

#### Observed
A message appears saying:
>Could not undo entry "Finish Rectangle"

![could_not_undo_finish_rectangle](https://user-images.githubusercontent.com/13420573/118378035-34967500-b5d1-11eb-9b34-be39542bcc8b.gif)

#### System
Luna Paint 0.5.1
VSCode 1.56.2
Windows 10 Version 2004

**Comment by Tyriar** [comment]
Something off happens on delete instead of new layer as well
