### ISSUE TITLE
New layer makes drawing on previous layer look distorted

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#65]
Adding a new layer makes the drawing on the previous layer look distorted.

### reproduction steps
- add a new layer
- draw a something
- add a new layer

### expected
the previous layer should look unchanged

### observed
the previous layer becomes distorted

![new_layer_distorts_previous_layer](https://user-images.githubusercontent.com/13420573/118378477-7b399e80-b5d4-11eb-88da-6eb128b4eb99.gif)

### note
selecting a layer with a drawing, shows it correctly.

### system
Luna Paint 0.5.1
VSCode 1.56.2
Windows 10 Version 2004

**Comment by Tyriar** [comment]
I spotted this as well, it actually only happens on my macbook, not my Windows machine. @duianto what type of graphics card do you have?

**Comment by duianto** [comment]
GeForce GTX 550 Ti

**Comment by Tyriar** [comment]
Curious that it doesn't happen on my Windows box, it even happens on my mac with really small images so it's not hitting memory limits. Will keep looking...

**Comment by Tyriar** [comment]
Actually managed to repro on my Windows machine, it's just a different/worse result on mac 🤔

**Comment by Tyriar** [comment]
Verified this is not due to VS Code's Electron 11->12 update

**Comment by Tyriar** [comment]
It only happens on images of a certain size, it happens on 800x600 but not 32x32

**Comment by Tyriar** [comment]
That was a challenge lol, the bug ended up being tiled textures which are only used for bigger images were using the wrong dimensions and being stretched. Thanks for reporting!
