### ISSUE TITLE
Says image saved on disk right after a save

### ISSUE THREAD

**Issue by lramos15** [lunapaint/vscode-luna-paint#73]
1. Open an image
2. Make an edit
3. Save the image
4. 🐛 Says image changed on disk and I must reload. Even though the change was caused by me
![recording](https://user-images.githubusercontent.com/4544166/120815884-4018f400-c51e-11eb-98cd-6d112071cc52.gif)

**Comment by Tyriar** [comment]
I think this is related to virtual fs providers
