### ISSUE TITLE
Zoom to infinity

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#76]
Issue Type: <b>Bug</b>

The zoom tool breaks, when zooming in with the zoom rectangle to many times.

### Reproduction steps

1. Select the zoom tool (z).
2. Zoom in, by drawing a rectangle with the left mouse button.
3. Move the mouse pointer to the top left of the middle of the image.
4. Hold down the left mouse button.
5. Move the mouse to the bottom right from the left mouse button down location.
6. Release the left mouse button.
7. Repeat the zoom in steps above from step 3.

The smaller the rectangle, the faster it zooms.

### Actual Behavior

The bottom right corner of the VSCode window shows that the zoom level increases quickly.
Up to at least 20 numbers.

Eventually it says `Infinity%`,
and the image shows the transparency checkerboard pattern.

Right mouse button clicking on the canvas to try to zoom out,
changes the bottom right zoom level to: `NaN%`
and the mouse position changes to: `NaN,NaN`

It doesn't seem possible to zoom back out by right clicking,
or by `ctrl mouse wheel` zooming out.
Nothing changes after 10+ times of either zoom out methods.

But it is possible to restore the image zoom level,
by right clicking on the layer and choosing:
`Fit layer to window [Alt+click]`
(Or by `Alt left mouse button clicking` on the layer)

![zoom_to_infinity](https://user-images.githubusercontent.com/13420573/121734575-3e8a9580-caf5-11eb-9a2f-c380c4012bb1.gif)

### Expected
The zoom tool rectangle should probably have a max zoom level,
like the `ctrl mouse wheel` zooming, which stops at `10000%`.

### Notes
In the recording a corner of a bright pixel is zoomed in on,
to show that the pixel grid lines seem to become offset from the edge of the pixel,
but it was probably understandable, since it's unlikely that it was intended to 
handle huge zoom levels.

Extension version: 0.6.0
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.96GB (7.17GB free)|
|Process Argv|--crash-reporter-id 59a302e3-5caa-4bda-8390-b451e1103e43|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehovct:30309550
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by Tyriar** [comment]
Actually just fixed this today 😉
