### ISSUE TITLE
Undo history breaks cropping to full dimensions

### ISSUE THREAD

**Issue by duianto** [lunapaint/vscode-luna-paint#79]
Issue Type: <b>Bug</b>

Temp panning (`space` held) after cropping, breaks undo history.

### Reproduction steps

1. Open an image.
2. Select the crop tool.
3. Draw a crop rectangle.
4. Hold down `space`.
5. Hold down the `Left mouse button`.
6. Move the mouse button to pan the image.
7. Release the Left mouse button.
8. Select the pencil tool.
9. Draw on the canvas

### Actual Behavior

The History window doesn't show any new entries for the pencil.

The crop can be undone by clicking on `Open Image` in the history window,
or pressing: `ctrl z`.

And the crop can be redone by clicking on `Crop` in the history window,
or by pressing `shift ctrl z` (or `ctrl y`).

But the history window doesn't show any new entries for any tool uses.

![undo_breaks_after_temp_hand_pan_after_crop](https://user-images.githubusercontent.com/13420573/121744113-b4492e00-cb02-11eb-9c4f-de062bd050c2.gif)

### Expected
The undo history shouldn't break after temp panning after having cropped.

Extension version: 0.6.0
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.96GB (7.17GB free)|
|Process Argv|--crash-reporter-id 59a302e3-5caa-4bda-8390-b451e1103e43|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehovct:30309550
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by Tyriar** [comment]
Good find, this is in the console:

```
vscode.main.js:1 Uncaught (in promise) Task "layer/cropToSelection" failed: Error: Cannot crop to selection of the same size
```

Think I know what happened, I'll make this a little more resilient so hopefully it doesn't happen again when something throws.

**Comment by Tyriar** [comment]
When this happens an edit could have partially happened so I think keeping the history entry is good here. It will be annotated with `(Error)` so it's possible to still undo it, even though it may have done nothing:

<img width="225" alt="Screen Shot 2021-06-12 at 3 59 18 AM" src="https://user-images.githubusercontent.com/2193314/121773723-92679f80-cb32-11eb-8f58-c74115bc1875.png">

If this ever shows up again it means there's a bug, but it shouldn't corrupt the editor.
