### ISSUE TITLE
Adopt `startEntries`?

### ISSUE THREAD

**Issue by JacksonKearl** [lunapaint/vscode-luna-paint#81]
Ref https://github.com/microsoft/vscode/issues/124304

This for you would might look like:
```
		"startEntries": [
			{
			"title": "Image",
			"description": "Create an empty .png file with specificed dimensions",
			"command": "luna.file.new"
		},
			{
			"title": "Icon",
			"description": "Create an empty .ico file with specificed dimensions",
			"command": "luna.file.newIcon"
		}
	],
```

![image](https://user-images.githubusercontent.com/8586769/122597153-d4578080-d01f-11eb-8da9-17a719af49e2.png)

**Comment by Tyriar** [comment]
Will add next weekend as I don't think it's in this insiders.

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/124124031-ce549d00-da2c-11eb-91fe-3f5bee8797d7.png)
