### ISSUE TITLE
Shared color information

### ISSUE THREAD

**Issue by Ghostling225** [lunapaint/vscode-luna-paint#82]
Issue Type: <b>Feature Request</b>

I would really like to see an option to share the current active color between open files. Right now I'm working on a multi-file project with a consistent color  scheme and have to pick a color on image A, copy the HEX data, paste it to the Palette window on image B and paint with the color. It would be much more convenient to just pick a color on image A and have it switched on image B too.

Extension version: 0.6.0
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Tyriar** [comment]
Might be able to get to this in 0.8. Not much state is shared across files right now, it would be good to do the same for tool options.
