### ISSUE TITLE
Errors on getting started page

### ISSUE THREAD

**Issue by chrisdias** [lunapaint/vscode-luna-paint#97]
Install into `github.dev`
On Welcome Page, click on "Pencil Tools" or "Selection Tools" (anything besides "Interface Overview"
Result:

![image](https://user-images.githubusercontent.com/1487073/131172362-9d38bdbc-a436-4445-a720-2f4ec4ceca63.png)

**Comment by JacksonKearl** [comment]
Upstream should be fixed.

**Comment by Tyriar** [comment]
Still happening, guess it's not deployed yet

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/135656560-5a53a293-3a1d-45a7-8734-56d81f387d3b.png)
This is what I;m seeing

**Comment by Tyriar** [comment]
I tried on github.dev
