### ISSUE TITLE
Capitalized .PNG Extension Failing on Codespaces and Desktop VS Code

### ISSUE THREAD

**Issue by Francois-Laberge-Bose** [lunapaint/vscode-luna-paint#98]
Using the latest Luna Paint for my Codespace I get a failure when trying to edit a file with .PNG as it's extension. Here's a video demonstrating it. 

https://user-images.githubusercontent.com/34040155/131174608-d8a82563-5638-48bb-975a-93e424cca939.mov

 - I believe I have Luna Paint set as the default editor for png files.
 - Here's the repo I used to demonstrate this. You'll need to install Luna Paint obviously.

**Comment by Francois-Laberge-Bose** [comment]
@Tyriar I'm not seeing any commit fixing this. The 6e467db hash doesn't exist.

**Comment by Tyriar** [comment]
The repo is actually closed source, I guess it's a github bug that the commit hash is showing up at all 😕

**Comment by Tyriar** [comment]
Created https://github.com/github/feedback/discussions/5361 for GH

**Comment by Francois-Laberge-Bose** [comment]
Ah, makes sense!
